config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :reservations, only: [:new, :create]

  get 'lamaisonthai', to: 'pages#lamaisonthai', as: :lamaisonthai

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < MailForm::Base
  attribute :name,        :validate => true
  attribute :email,       :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone,       :attachment => true
  attribute :pax,         :attachment => true
  attribute :date,        :attachment => true
  attribute :time,        :attachment => true
  attribute :nickname,    :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "New reservation",
      :to => "benoit.bessiere@me.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # protect_from_forgery with: :exception
 # before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def catering
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(params[:reservation])
    if @reservation.deliver
      flash[:success] = "Email sent !"
    else
      flash[:alert] = "Cannot send reservation"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>La Table des Artisans</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/lamaisonthai.html.erb
<div class="wrapper-catering">
  <div class="container">
    <h2>La Maison Thaï</h2>
  </div>
</div>

app/views/reservations/create.html.erb
<div class="wrapper-reservation">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="title-header text-center">
          <h2>Thank you for your reservation !</h2>
        </div>
        <br>
        <div class="title-subheader text-center text-muted">
          <p class="title-subheader">A confirmation will be mailed to you shortly.</p>
          <br>
          <p>Looking forward to welcoming you in our restaurant.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="wrapper-reservation">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="title-header text-center">
          <h2>Make online reservation</h2>
        </div>
        <br>
        <div class="title-subheader text-center text-muted">
          <p class="title-subheader">NB: For today's reservation,<br> please contact the restaurant at +41.22.710.3014</p>
        </div>
      </div>
    </div>
    <div class="row justify-content-lg-center">
      <div class="col-lg-8">
        <div class="reservation-form my-2">
          <%= form_for @reservation do |f| %>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :name, class: "sr-only" %>
                  <%= f.text_field :name, placeholder: "Enter your name",required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :email, class: "sr-only" %>
                  <%= f.email_field :email, placeholder: "Email", required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :phone, class: "sr-only" %>
                  <%= f.text_field :phone, placeholder: "Phone number", required: true %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.label :pax, class: "sr-only" %>
                  <%= f.text_field :pax, placeholder: "How many people ?", required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :date, class: "sr-only" %>
                  <%= f.date_field :date, required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :time, class: "sr-only" %>
                  <%= f.time_field :time, required: true %>
                </div>
                <br>
                <div class="hidden">
                  <%= f.label :nickname %>
                  <%= f.text_field :nickname, hint: 'Leave it blank' %>
                </div>
              </div>
              <div class="col">
                <div class="text-center">
                  <%= f.submit 'Reserve a table', class: "button-reservation" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-resto">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo-title.png", height: 50 %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "Reservation", new_reservation_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Menu", "#menu", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Catering", lamaisonthai_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", "#contact", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          EN
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "FR", "#", class: "nav-link" %>
          <%= link_to "TH", "#", class: "nav-link" %>
        </div>
      </li>
    </ul>
  </div>
</div>